I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 55, in script call
    call episode_2
  File "game/scripts/episode_2/episode_2.rpy", line 12, in script call
    call call_parents
  File "game/scripts/episode_2/episode_2.rpy", line 30, in script call
    call phone_call
  File "game/scripts/episode_2/episode_2.rpy", line 64, in script
    $ phone.shake(0.1, 0.1, 5, False)
  File "game/scripts/episode_2/episode_2.rpy", line 64, in <module>
    $ phone.shake(0.1, 0.1, 5, False)
AttributeError: 'Image' object has no attribute 'shake'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 55, in script call
    call episode_2
  File "game/scripts/episode_2/episode_2.rpy", line 12, in script call
    call call_parents
  File "game/scripts/episode_2/episode_2.rpy", line 30, in script call
    call phone_call
  File "game/scripts/episode_2/episode_2.rpy", line 64, in script
    $ phone.shake(0.1, 0.1, 5, False)
  File "C:\Program Files\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Program Files\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/scripts/episode_2/episode_2.rpy", line 64, in <module>
    $ phone.shake(0.1, 0.1, 5, False)
AttributeError: 'Image' object has no attribute 'shake'

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
junior's way 0.2
Sun Dec 10 04:23:14 2023
